config:
  github:owner: haleyrc
  github:token:
    secure: AAABAIVhEhPpRmv/6D3hp+d96atBDhMvXt3KyxQ0HpesxWhH3ftkD/Hz/5dlOIVgxhWPqO6BmZywB7DvGDGeixcsw5VnomieGMJnc8T/KfElEaV2x7tzjH2qDX8oCVkngQxvEgeta2Ey8s8lTJGVC/uwfxsAyTwqKKFUEkc=
